name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_native_splash: ^2.3.10
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  animate_do: ^3.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    

flutter_native_splash:
  color: "#E0ADF5"
  image: assets/Bungaungu1.png
  android: true
  ios: true
